source: _src
destination: htdocs

scss:
  source: _src/_scss
  destination: css

js:
  source: _src/_js
  destination: js
  targets:
    script.js:
      min: script.min.js
      files:
        - main.js
    jquery.min.js:
      files:
        - lib/jquery.min.js
    jquery.maximage.min.js:
      files:
        - lib/jquery.maximage.min.js
    jquery.cycle.all.js:
      files:
        - lib/jquery.cycle.all.js
    fixed.js:
      files:
        - lib/fixed.js
    index.html.js:
      files:
        - index.html.js
