source: _src
destination: htdocs

scss:
  source: _src/_scss
  destination: css

js:
  source: _src/_js
  destination: js
  targets:
    script.js:
      min: script.min.js
      files:
        - main.js
    jquery.min.js:
      files:
        - lib/jquery.min.js
    jquery.maximage.min.js:
      files:
        - lib/jquery.maximage.min.js
    jquery.cycle.all.js:
      files:
        - lib/jquery.cycle.all.js
    fixed.js:
      files:
        - lib/fixed.js
    jquery.fancybox-1.3.4.pack.js:
      files:
        - lib/jquery.fancybox-1.3.4.pack.js
    jquery.mousewheel-3.0.4.pack.js:
      files:
        - lib/jquery.mousewheel-3.0.4.pack.js

    index.html.js:
      files:
        - index.html.js
    stylist.html.js:
      files:
        - stylist.html.js
    haristyle.html.js:
      files:
        - haristyle.html.js
    products.html.js:
      files:
        - products.html.js
    about_us.html.js:
      files:
        - about_us.html.js
